# Generated by Django 5.0 on 2023-12-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('volunteer', 'Volunteer'), ('staff', 'Staff'), ('admin', 'Admin')], max_length=20)),
            ],
        ),
    ]
