# Generated by Django 5.0 on 2023-12-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_shirt_size_alter_user_phone_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('volunteer', 'Volunteer'), ('staff', 'Staff'), ('admin', 'Admin')], default='volunteer', max_length=20),
        ),
    ]
